name: Setup Node.js
description: Setup Node.js with node_modules cache

inputs:
  node-version:
    description: Node.js version to use (overrides node-version-file)
    required: false
  node-version-file:
    description: File containing the Node.js version (e.g., package.json, .nvmrc)
    required: false
    default: package.json
  registry-url:
    description: npm registry URL
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && inputs.node-version-file || '' }}
        registry-url: ${{ inputs.registry-url }}

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v5
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
